# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onnx_serving_grpc/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'onnx_serving_grpc/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!onnx_serving_grpc/inference.proto\x12\x10onnxserving.grpc\"\r\n\x0bLiveRequest\"\x0e\n\x0cReadyRequest\")\n\x0bStatusReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\"G\n\x0ePredictRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x03 \x01(\t\"\xa3\x01\n\x0cPredictReply\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12>\n\x08metadata\x18\x03 \x03(\x0b\x32,.onnxserving.grpc.PredictReply.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xed\x01\n\x10InferenceService\x12\x44\n\x04Live\x12\x1d.onnxserving.grpc.LiveRequest\x1a\x1d.onnxserving.grpc.StatusReply\x12\x46\n\x05Ready\x12\x1e.onnxserving.grpc.ReadyRequest\x1a\x1d.onnxserving.grpc.StatusReply\x12K\n\x07Predict\x12 .onnxserving.grpc.PredictRequest\x1a\x1e.onnxserving.grpc.PredictReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onnx_serving_grpc.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREPLY_METADATAENTRY']._loaded_options = None
  _globals['_PREDICTREPLY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LIVEREQUEST']._serialized_start=55
  _globals['_LIVEREQUEST']._serialized_end=68
  _globals['_READYREQUEST']._serialized_start=70
  _globals['_READYREQUEST']._serialized_end=84
  _globals['_STATUSREPLY']._serialized_start=86
  _globals['_STATUSREPLY']._serialized_end=127
  _globals['_PREDICTREQUEST']._serialized_start=129
  _globals['_PREDICTREQUEST']._serialized_end=200
  _globals['_PREDICTREPLY']._serialized_start=203
  _globals['_PREDICTREPLY']._serialized_end=366
  _globals['_PREDICTREPLY_METADATAENTRY']._serialized_start=319
  _globals['_PREDICTREPLY_METADATAENTRY']._serialized_end=366
  _globals['_INFERENCESERVICE']._serialized_start=369
  _globals['_INFERENCESERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
